### ISSUE TITLE
Number of boxes to appear before “load more”: 

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#102]
For now, the number of boxes appearing before “load more” differs from one page to another. This needs to be coherent with a number of 9 boxes shown in each page (educate, read, participate) except for the career page : 3 boxes shown for each section.

**Comment by vehrlich** [comment]
It's strange but I can see 6 boxes in 'Educate' section. But only if I'm logged into administration. If I log out I can see 9 boxes.
So normal user can see right number of boxes.
But of course it's strange.
