### ISSUE TITLE
Add Bulgarian to the website

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#111]
If we can, we should add Bulgarian as a language for the website.
Thanks!

**Comment by vehrlich** [comment]
@Korczynska  It's possible. There is somewhere spreadsheet with translations. Do you want to translate text there or should I send you text file with phrases to translate ?

**Comment by Korczynska** [comment]
Hey Vavlac, do you have the spreadsheet? Otherwise, we will find it. Thanks!

**Comment by vehrlich** [comment]
@Korczynska https://docs.google.com/spreadsheets/d/10lLgvZnX0eW6mR2gusvTHYqWA6PXEOMLa9af6w3xwvI/edit#gid=633367598

**Comment by vehrlich** [comment]
@Korczynska https://docs.google.com/spreadsheets/d/1BvGWUWs-hi7PKElkJMXFE3sQ4qS4X2Y5kd9SJFSdiE0/edit
