### ISSUE TITLE
Career profile issues

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#112]
spotted few things on the career profile pages: 
- there is a "interview" field on the right column and there should be a link to the interview pages related. It doesnt  appear in the back office.
- it seems that some PDF don't follow the good template: the material engineer title is in the wrong colour, it should be blue instead of violet. Also the category logos are a bit cut on the front page.
Thanks!

**Comment by vehrlich** [comment]
@Korczynska  It does not appear in administration, because this information is through database relations. 
e.g. Career of astrochemist shows links to all astrochemist interviews.

**Comment by vehrlich** [comment]
@Korczynska all careers should have the same color (turquoise). I've checked material engineer PDF (http://www.space-awareness.org/media/careers/download/career-en-who-materials-engineer.pdf) and Title should be fine. If you will find any pdf (from careers) with wrong color, it could be old generated, and I should remove it.

**Comment by vehrlich** [comment]
@Korczynska yes logos are strange on front page. It is the same as in all other PDFs (from articles and so). I have to figure it why - because there are ok on print preview.

**Comment by vehrlich** [comment]
Only relevant is PDF's categories icons.
https://github.com/unawe/spaceawe/issues/119
Closing this.
