### ISSUE TITLE
Typo on title

### ISSUE THREAD

**Issue by unawe** [unawe/spaceawe#115]
Could you please change the title "  FORMATIVE ASSESSEMENT TOOLS "  ->  FORMATIVE ASSESSMENT TOOLS : http://www.space-awareness.org/en/skills/ ? (Pedro Russo)

**Comment by vehrlich** [comment]
Done. 
This values could be changed in adminstration
http://www.space-awareness.org/cs/admin/develop/assessmentmetadataoption
