### ISSUE TITLE
Issue top bar

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#116]
Hi Vaclav,

it seems that when you make the website window smaller on the horizontal axis, at some point the tab Participate goes to the row below, see image below 

![screen shot 2017-04-24 at 5 28 08 pm](https://cloud.githubusercontent.com/assets/23382266/25344792/7cc77be8-2913-11e7-8bc1-4206ddcf6c19.png)

But if you scroll down, it disappears because only the top row remain, see image

![screen shot 2017-04-24 at 5 30 11 pm](https://cloud.githubusercontent.com/assets/23382266/25344917/d979587a-2913-11e7-93f5-5bf2e059e7cf.png)

Is it possible to fix that please?

**Comment by vehrlich** [comment]
done with #114
