### ISSUE TITLE
Check header menu item spacing in translations

### ISSUE THREAD

**Issue by slowe** [unawe/spaceawe#16]
Their positioning in Greek was particularly bad.

**Comment by slowe** [comment]
@Korczynska How should the design of the main menu work for languages that have wide menu item names? For instance, German uses "Berufliche Perspektiven" for "Careers" and that means there isn't enough space for "Teilnehmen" (Participate).

**Comment by slowe** [comment]
Rafa says we should ask for a German translation that is shorter. See issue #42 too.

**Comment by vehrlich** [comment]
All items are in one line. Only problem is with German translation of Careers. Then left side feels like it's bigger. Feel free to create new Issue with provided shorter translation or to reopen this one.
