### ISSUE TITLE
News page: All thumbnails appears squeezed in and news titles cannot be read

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#25]

**Comment by slowe** [comment]
@Korczynska This (and issue #26) should be solved now. This is how it looks in Chrome for me.
![screen shot 2016-09-12 at 13 06 56](https://cloud.githubusercontent.com/assets/299787/18435226/de450ce4-78e9-11e6-8b44-187fd1185a10.png)
Please mark this as closed if you are happy with it.

**Comment by Korczynska** [comment]
Me too, very nice now :) Thanks.

**Comment by slowe** [comment]
Great. I'll mark this as closed then.
