### ISSUE TITLE
•    Read, Participate, Educate: Same issue as News with thumbnails being squeezed in and making titles un readable

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#26]

**Comment by slowe** [comment]
![screen shot 2016-09-12 at 13 05 06](https://cloud.githubusercontent.com/assets/299787/18435168/9030ddf8-78e9-11e6-8ff4-5f6a07107467.png)

@Korczynska This should now be solved in Chrome. Please review e.g. http://www.space-awareness.org/en/scoops/ and mark this as closed if you think it looks OK now.

**Comment by Korczynska** [comment]
Solved!

**Comment by slowe** [comment]
Hooray!
