### ISSUE TITLE
Know us: Text comes on top of left image, gets even worse if you zoom into the page

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#27]

**Comment by slowe** [comment]
Can you provide a screenshot for this? I can't see what you mean.

**Comment by slowe** [comment]
@Korczynska Can you provide a screenshot for this? I can't see what you mean

**Comment by slowe** [comment]
![screen shot 2016-09-12 at 13 00 20](https://cloud.githubusercontent.com/assets/299787/18435061/ebafc352-78e8-11e6-9948-0fb13a2a9045.png)
@Korczynska This should now be fixed in both Chrome and Firefox. Please check http://www.space-awareness.org/en/about/ and let me know.

**Comment by Korczynska** [comment]
It is solved for me.  I will check with my colleagues who pointed this out and let you know if they still have issues.

**Comment by slowe** [comment]
If they still have issues, please reopen this.
