### ISSUE TITLE
educate section/actvity pages: italic, bold and other features in text disappeared

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#28]

**Comment by slowe** [comment]
![screen shot 2016-09-12 at 13 08 56](https://cloud.githubusercontent.com/assets/299787/18435272/1a035952-78ea-11e6-9fae-11ebc8f430d9.png)

@Korczynska Headings are now bold. Lists now have bullet points. I'm not sure what should be italic. Let me know what still needs fixing.

**Comment by Korczynska** [comment]
This is well working as well! Thanks.

**Comment by slowe** [comment]
OK. If you think it is OK (and isn't missing italics somewhere) I'll mark it as closed. You can re-open it if you think it still needs something fixing.
