### ISSUE TITLE
Develop section: modules of MOOCs appear from the latest

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#29]
Develop section modules of MOOCs start their appearance in the list below the title from the latest  – for example, from Module 5 to Module 1 for the first MOOC instead of Module 1 to 5.

**Comment by slowe** [comment]
There is no obvious reason why the live site is doing this. Neither my local copy nor my VirtualBox version were doing this. To 'fix' the problem I've added a "reverse" to the Django template. This shouldn't be the solution. Perhaps @bruno-rino knows why. Meanwhile, it works so I'm closing this issue.
