### ISSUE TITLE
Formating of activities

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#31]
**Feedback from a partner who filled in new activities (www.space-awareness.org/activities):**
The options of formatting the entries are very limited (figures: scaling, captions, tables, cross references, text formatting, structured lists, equations). Luckily, the bulleted lists are back and are being displayed. However, numbered lists show up only as bulleted lists.
The italic formatting of the text still does not work; the text is displayed in normal style. I would love to have that opportunity to improve the paragraph labelling.

**Comment by slowe** [comment]
@Korczynska Yes I can make text italic. However, I need to know what parts of the text are supposed to be italic to do that.

**Comment by slowe** [comment]
@Korczynska Captions, tables, cross references, text formatting and structured lists should already be possible in Markdown (they may not be then translated by the website; at the moment I don't know where the translation is done). 

  * Figure:scaling: I'm not sure exactly what is wanted. Scaling to what?
  * Equations: at the moment these seem (as far as I can tell) to get added as images so exist. What is the request?

Please confirm that italic text and numbered lists now work. Thanks.

**Comment by slowe** [comment]
Tables: ✓
Italic text: ✓
Bulleted lists: ✓
Numbered lists: ✓
Captions: ?
Image scaling: ?
Paragraph labelling: ?
Equations: requires thought as it'll have to work in the PDF too

**Comment by slowe** [comment]
Tibisay, could you find out what is meant by "captions", "image scaling" and "paragraph labelling"? Thanks.

**Comment by slowe** [comment]
@jorgegrivero Would you be able to work out what was required for "captions", "image scaling" and "paragraph labelling"? I would like to be able to close issues if I can.

**Comment by vehrlich** [comment]
Text is accepted as markdown so everything is possible to do with markdown is possible to do within Activities
https://en.wikipedia.org/wiki/Markdown
Limitations of the markdown are limitations for formatting our activities. I'm closing this issue. If you want to have some kind of  WYSIWYG editor, please create issue for it.

Equations are bit harder. I'm looking for solution. I'll create new issue for equations only. It must be implemented in a way that PDF generator will handle it.
