### ISSUE TITLE
combine the search filters for activities

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#32]
You cannot combine the search filters, e.g. selecting only "Navigation" and "secondary level". 

If you try to do this you get this:
1. select "Navigation"
2. select "Secondary"
   Result: all categories at secondary level (not only "Navigation")
3. select "Secondary"
4. select "Navigation"
   Result: Error message: "The requested URL /en/activities/level/secondary/category/navigation/ was not found on this server."

**Comment by slowe** [comment]
Now replaced by issue #54
