### ISSUE TITLE
Download a PDF option of an activity

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#33]
For example: 
http://www.space-awareness.org/en/activities/6024/greenhouse-effect/
On the right column appears the option "download".

**Two issues:** 
- 1/ this option is only available in the English website, it should appear for all languages
- 2/ the PDF is not the final one that should be applied and has some issues (name of authors does not appear, weird logo on page 2...) 
  see PDF example: 
  http://www.space-awareness.org/media/activities/download/activity-6024en-greenhouse-effect.pdf

See the PDF as it should appear in the ZIP attached. 
[PDF Activity example.zip](https://github.com/unawe/spaceawe/files/477025/PDF.Activity.example.zip)

**Comment by slowe** [comment]
@Korczynska This is quite advanced for me as it involves the back-end part of the site. It will take a while to explore this.

**Comment by Korczynska** [comment]
Do you think you could do this in the coming 10 days?

**Comment by slowe** [comment]
I haven't been able to work out how to change the style of the PDF. I thought it might be in https://github.com/unawe/spaceawe/blob/master/static/scss/print-activities.scss but changing that file doesn't seem to have any affect.

**Comment by slowe** [comment]
@bruno-rino When I change `print-activities.scss` or `activity_detail_print.html` it doesn't seem to have any affect. Is there caching happening somewhere?

**Comment by vehrlich** [comment]
@Korczynska There is a picture of planets and their trajectories in example PDF from ZIP file. Do you have this graphic or if it is in repo already which one is it, please?
