### ISSUE TITLE
MOOC page design - Urgent

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#38]
The design of the MOOC page is not good: http://www.space-awareness.org/skills/
See: https://www.dropbox.com/s/brz6e9s49fmg7h7/SpaceAw_web_v5_Develope.pdf?dl=0 

Additional tasks: 
- Take out the “enroll” box from the text box and place it under/next to the "+" box to make it directly visible without having to clik on + .
- MOOC 4 `Navigation through the ages` should be moved in second position and be renamed MOOC 2. The other two MOOCs are renamed 3 and 4 accordingly (no order yet).

**Comment by slowe** [comment]
@Korczynska The official design has a "more info" button underneath the Mooc. The current design uses a +/⨯ button within the Mooc table. Following the first part of the request, I will change to the official design but you will need to get translations for "more info".

For additional task 2, it should be noted that the page is created from templates. To change the position, you set this in the admin interface for a mooc. The Mooc numbers are determined from the order on the page. If you want, we can not say "Mooc 1", "Mooc 2" etc and just show the titles. What do you think?

**Comment by slowe** [comment]
I won't implement the hover effect that changes the background colour of a row to a darker grey as mouse events like that suggest that there is interactivity and, in this case, clicking a module does nothing so will be confusing.

**Comment by slowe** [comment]
I went into the admin interface and changed the order.

**Comment by Korczynska** [comment]
Thank you Stuart, the only issue is that clicking on see more, you cannot close the box anymore once it is open. 
Can this be changed? Maybe keeping +/- instead of see more but keep the current place?

The page looks much better now!

**Comment by slowe** [comment]
If the "see more" button is changed to a plus/minus button it will be more confusing from a user interface point-of-view. We have already disconnected the button from the element being expanded. Losing the explanatory text ("see more") will give even less context to the button. I suspect fewer people will click it.

**Comment by slowe** [comment]
I'm going to mark this as closed. It can be re-opened if necessary.
