### ISSUE TITLE
Search option not visible on home page

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#40]
Search option should appear on the home page on the upper right corner - other side than language option.

**Comment by slowe** [comment]
If it goes on the left-hand side, where does it go in a narrow screen view? In a narrow screen view, the main menu uses a hamburger menu on the left-hand side.

**Comment by Korczynska** [comment]
I think that in the design, it is actually next to language.
You can also see this with Rafa, he made the design.

**Comment by slowe** [comment]
A bigger reason why there is no search visible is because the search results were never properly implemented. This is a back-end issue that I am trying to look at.

**Comment by vehrlich** [comment]
Duplicate with #98
