### ISSUE TITLE
PDF download option for a Space Scoop

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#43]
Space Scoop http://www.space-awareness.org/en/read 
- Apply final design to the PDF to download the article as designed by Rafa: https://www.dropbox.com/s/ulvwc80qo3133qr/PDF%20Space%20Scoop%20new02.pdf?dl=0
- If possible, the option to download the article should appear for all languages and directly recognize if the article is available in the language of navigation (eg: I am in a french website, if the article is only available in English, I can download a PDF in English and if the translation is available in french, the PDF I download is in french.

**Comment by slowe** [comment]
The website was only disabling PDF download for languages where there was no translation. I've changed it so that it will download a PDF for all languages. If there is no translation, it uses the default text.

**Comment by slowe** [comment]
I don't know how to change the PDF style. Am I correct in thinking the only change of style required is the addition of the background image?

**Comment by vehrlich** [comment]
I've changed styling to be as close as possible to Rafa's template.
There was also necessary change generating (it's different from activities)
