### ISSUE TITLE
Know up page: map of partners

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#44]
Know us: http://www.space-awareness.org/en/about/

Update map with final instructions: some dots should appear in two colours, this should be added to the caption: 2 colours (half blue/half orange) = national contact and project partner. 

This applies to “House of Astronomy” in Germany “Ellinogermaniki Agogi” in Greece “Ciencia Viva” in Portugal

**Comment by slowe** [comment]
I've made the dual icon appear. For some reason the dual institution in Portugal is not the "Ciencia Viva". I don't know where you set those properties. Presumably you can update the properties of the institutions in the admin interface so I'll mark this as closed.
