### ISSUE TITLE
Category pages - load more button

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#45]
Category pages: 
www.space-awareness.org/en/categories/earth/
www.space-awareness.org/en/categories/space/
www.space-awareness.org/en/categories/navigation/
www.space-awareness.org/en/categories/heritage/

Add a “Load more” button for each resource selection - this could link to the related resource page already sorted out in the related category. 
eg: load more under space scoop in the category Navigation goes to Space Scoop page/Navigation

**Comment by slowe** [comment]
![screen shot 2016-12-01 at 19 11 22](https://cloud.githubusercontent.com/assets/299787/20808306/fe148064-b7f9-11e6-9eba-c1226ba41547.png)
