### ISSUE TITLE
Problem with PDF layout activity Blue Marble in empty space

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#50]
There is a problem with the following activity
http://www.space-awareness.org/nl/activities/1412/blue-marble-in-empty-space/

The layout of the automatically generated pdf is not working properly 

http://www.space-awareness.org/media/activities/download/activity-1412nl-blue-marble-in-empty-space.pdf

**Comment by slowe** [comment]
I am really stuck on being able to change how the PDFs are generated. I am having the same problem with issue #33.

**Comment by vehrlich** [comment]
@jorgegrivero problem is repeating logo and header (according PDF in ZIP from https://github.com/unawe/spaceawe/issues/33)

I've disabled logo (there was not header) in current PDFs. So there should not be any ghost logo over text. 
But I have to investigate how to set header (and logo again) which is repeating on every page.

**Comment by slowe** [comment]
I think (check with @jorgegrivero) that there is supposed to be a common header and footer on every page as shown in the example linked in the first comment of issue #33.

**Comment by vehrlich** [comment]
Sure, it's like you said. I'll find how to set the header to proper placement on each PDF page. For now, I've just disabled a part of the code which caused overlay error. (better without logo than ugly one overlaying text)

**Comment by jorgegrivero** [comment]
Hi Vaclac, thanks for this. I agree, in the meantime is best to not have the logo until you figure it out how to set proper header with the logo.

**Comment by vehrlich** [comment]
it should be with logo now

http://www.space-awareness.org/media/activities/download/activity-1412nl-blue-marble-in-empty-space.pdf
