### ISSUE TITLE
Issue language bar/drop down menu for Google Chrome 

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#53]
It seems that there is an issue with the language bar/drop down menu in the top right corner of the website for Google Chrome and for mobile version of the browser, the issue appeared using a tablet that runs on Android 4.4.2. Check below screenshots for Chrome and Mozilla.

![chrome_view_lang_issue](https://cloud.githubusercontent.com/assets/23382266/20344840/a7071996-abf4-11e6-8b6f-3e06b7064cd4.jpg)

![mozilla_view_no_issues](https://cloud.githubusercontent.com/assets/23382266/20344865/c42d2060-abf4-11e6-9c94-342c4ed358b7.jpg)

I don’t have a screenshot for the mobile browser issue, but it looks the same in the landscape mode as for the Chrome. For portrait mode the languages appear properly.

Many thanks in advance for addressing this issue.

**Comment by slowe** [comment]
@jorgegrivero  Thanks for the screenshots. I'll investigate.

**Comment by slowe** [comment]
This should be solved in Chrome. Tested on the Desktop browser and on mobile (Chrome 50.0.2661.89; Android 6.0.1
![screen shot 2016-11-16 at 13 47 49](https://cloud.githubusercontent.com/assets/299787/20349823/034e50ca-ac04-11e6-9ec7-408ff19a5ec2.png)
)
