### ISSUE TITLE
Filtering of resources does not work

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#54]
It seems that combining topics and levels does not work.

If you combine filtering of topics and levels on http://www.space-awareness.org/en/activities/, you either get an error message or the result is empty or the filtering parameters are being reset.

**Comment by vehrlich** [comment]
@jorgegrivero before I deploy it - I made changes and now you can filter by categories and levels. If no category is set, then selected level for all categories is shown. 
If you filter level of category and then you select another one category, level is reset.

**Comment by jorgegrivero** [comment]
Ok, let me know when you deploy it so we can check it.

**Comment by jorgegrivero** [comment]
Hi Vaclac, looks good to me. I think we can close it.
