### ISSUE TITLE
Collapse text on sections of Activities page

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#57]
There are new activities on the website that have a lot of text and we would like to make it possible that the text could be collapsed for each section. Do you think is it possible? Would that affect the PDF generation?

**Comment by slowe** [comment]
This can be done and doesn't affect PDFs. What should the user experience be like?

**Comment by jorgegrivero** [comment]
For instance taking a look at this activity http://www.space-awareness.org/en/activities/6031/ocean-acidification/

You can see sections like Evaluation or Background information are too long. The idea would be to have just one or two paragraphs and then "show more" option that open/collapse the whole text on the section without leaving the page.

See this page as an example https://ec.europa.eu/research/participants/portal/desktop/en/opportunities/h2020/topics/compet-6-2017.html

**Comment by slowe** [comment]
@jorgegrivero Sorry, I was just trying to understand if the problem could be addressed in a better way. Each section will need to be clicked/touched to expand but, once a section is opened, scrolling will probably still be required. I know that I would find it an annoying user interface (and it makes printing the page more awkward) but I probably don't represent a typical user. I'll implement a collapse for each section as asked and then you can see what you think.

**Comment by slowe** [comment]
Rafa sent the following screenshot for how it should look:
![screnshot_02](https://cloud.githubusercontent.com/assets/299787/20541782/820f5304-b0f6-11e6-87aa-9648690dfa47.png)
To keep the button in a fixed place he then suggested:
![screnshot_03](https://cloud.githubusercontent.com/assets/299787/20541785/843c051e-b0f6-11e6-9a97-13ab20c7cc3b.png)

**Comment by slowe** [comment]
This was Rafa's initial zebra banding.
![screen shot 2016-11-22 at 21 21 00](https://cloud.githubusercontent.com/assets/299787/20542479/a85266a2-b0f9-11e6-918e-e8cbd3217199.png)

**Comment by jorgegrivero** [comment]
The activities page look much cleaner now with the sections collapsed but as you said I think people might not realize that they are collapse. I think we might need the Read More/Read Less button

**Comment by slowe** [comment]
@jorgegrivero Can you provide translations of the text for them?

**Comment by jorgegrivero** [comment]
I will but I think in the meantime we can use the English version for all languages, in any case, so far the activities are only in English.

**Comment by slowe** [comment]
Screenshot showing changes requested by Rafa ![screenshot](https://cloud.githubusercontent.com/assets/299787/20808745/a416e3a2-b7fb-11e6-9bc0-c53d7063e015.jpg)

**Comment by slowe** [comment]
Now uses "Read more"/"Read less" buttons at the bottom of sections that have been collapsed. Can ignore the "20px" spacing requirement from Rafa as the button isn't to the side of the section title.
