### ISSUE TITLE
Issues with map displaying information from Dissemination nodes

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#58]
On the map displaying information from Dissemination Contact nodes (http://www.space-awareness.org/en/about/), for some cases the information displayed is going over the box when the information is too long. See image attached 
![screen shot 2016-11-24 at 4 12 22 pm](https://cloud.githubusercontent.com/assets/23382266/20603294/26f0e41c-b261-11e6-94ba-efe02c64053f.png)

**Comment by slowe** [comment]
Should now be fixed.
![screen shot 2016-12-01 at 17 13 19](https://cloud.githubusercontent.com/assets/299787/20804107/8142846a-b7e9-11e6-8827-3b31e772fc42.png)

**Comment by slowe** [comment]
I also added a bit of padding between the logo and institution name.
