### ISSUE TITLE
Issue embeds translations

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#59]
Issue reported by Anastasiya:

I am experiencing troubles with correcting Czech translation for content of the website in the part which I have an access to in order to copy-paste the updated translation.

If you go to the Site Administration -> Embeds -> choose any category and click on language different from English, the text appears in English.

For example, I choose  about-033-navigation, click on de and German version is actually in English. The same appears for all languages.

However, on the website translations work. If I choose any language different from English, the translation works perfect.

I added screenshot to this email to make it more clear to you and Stuart.

![embeds_en](https://cloud.githubusercontent.com/assets/23382266/20624267/364dfc3c-b30c-11e6-8e0f-06148b596d0b.jpeg)
![embeds_cz](https://cloud.githubusercontent.com/assets/23382266/20624287/4b1c951a-b30c-11e6-9a60-ae60451b1334.jpeg)

**Comment by slowe** [comment]
@bruno-rino I don't know how the admin part of the site deals with translations. Any ideas?

**Comment by jorgegrivero** [comment]
Thanks Vaclac, I think we can close this issue.
