### ISSUE TITLE
Change Titles thumbnails interviews on website

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#66]
On the Careers Section (http://www.space-awareness.org/en/careers/) we would like to put the titles/teasers at the bottom of the thumbnails so they do not cross people’s faces. Is it possible to change this?

See below an example

![careerhub_interviews](https://cloud.githubusercontent.com/assets/23382266/21392768/bcbcb9ea-c791-11e6-99b2-923ab142509a.png)

**Comment by slowe** [comment]
Is someone going to make sure people's faces are always at the top of the thumbnails?

**Comment by slowe** [comment]
Also, because the "+" symbol was required to appear on hover, the text cannot be fully at the bottom of the thumbnail.

**Comment by slowe** [comment]
I had to put the "+" button at the top.
