### ISSUE TITLE
Translation Buttons "Read more/Read less"

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#72]
We gathered translations in all languages for the buttons here

https://docs.google.com/spreadsheets/d/12BI5ADctbmUoYGNR7bfeCx-2wyXAVfZSq7A6ILLpmkE/edit#gid=0

Is it possible to include them please?

**Comment by vehrlich** [comment]
#75 Solved

**Comment by jorgegrivero** [comment]
Great, I'll close it then.
