### ISSUE TITLE
Problems with career page

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#76]
On the Carrers page, on the section interviews there is problem at the bottom when you click on load more you get what you see on the images below

![screen shot 2017-01-23 at 12 00 39 pm](https://cloud.githubusercontent.com/assets/23382266/22201529/4b764818-e164-11e6-9aa6-a5b8278db7b7.png)
![screen shot 2017-01-23 at 12 00 46 pm](https://cloud.githubusercontent.com/assets/23382266/22201534/503b80a2-e164-11e6-86c7-e1cd5b610bae.png)

Instead of uploading the two remaining interviews, it includes again the categories and another banner. It also messes up the top banner with the different sections of the website

**Comment by vehrlich** [comment]
For now this issue could be considered as solved. But during testing I have newer issue.
After loading proper data in proper template, new items were loaded after old items (under red line). Old and new data were not joined. (picture shows more)
But this should be new issue.
![sp1](https://cloud.githubusercontent.com/assets/1701829/22229042/87fb1298-e1d5-11e6-88a2-043e3cbb74f8.png)
