### ISSUE TITLE
Sorting out by topics

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#80]
in the pages "careers" and "read" the options to sort out the resources by topic aren't working. When clicking on a topic i.g. "Our fragile planet" it goes to the related page on the section "resources". 
Ïnstead, we should stay on the page and get only the items related to the topic chosen.

In the career section, the option to relate a resource to a topic doesn't appear in the backoffice for each resource (interviews, profiles, webinars).

**Comment by vehrlich** [comment]
Carrers, read, educate stays on the same page now when filtering. This should be fixed.

Could you please explain more about relating resources to topics ?

**Comment by Korczynska** [comment]
When we enter an activity in the educate section in the backoffice, we can choose a Space Awareness Category (what I called topic): "space" "earth" "Navigation" "Heritage". 

In the related page of the website online: http://www.space-awareness.org/fr/activities/
we can click on "sort out by category" on the icons "Navigation" (Navigation through the ages) "Earth" (Our fragile planet) "heritage" (The journey of ideas) and "space" (Our wonderful universe) and see only the activities for examples in the category "navigation". 

The same system should apply to the pages careers, read, and participate. 
In the participate page, the system was working before but now I see that the icons representing each category don't even appear any more. 

At another level: on the home page, you can see again the four icons representing the categories "Navigation" "Earth" (=Our fragile planet) "heritage" (The journey of ideas) and "space" (Our wonderful universe). When you click on one of them, you go to this special category page where you should find all material related to the category.

**Comment by Korczynska** [comment]
Let me know if you need more details on that, we can discuss on skype or slack any time!

**Comment by vehrlich** [comment]
Careers, read, educate and games now should proper filter and stay on the same page.
