### ISSUE TITLE
PDF of activities - final design

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#84]
Hello,
Thank you very much for correcting the PDF of activities.  

Maybe you will be able to implement it with the design the PDF should actually look like: 
[PDF Activity example.pdf](https://github.com/unawe/spaceawe/files/754182/PDF.Activity.example.pdf)
(except the line on the first page "*tested by teachers*") 

The last developer couldn't manage to implement this nicer version... 
Thank you,
Audrey

**Comment by vehrlich** [comment]
Sure. It is mentioned in https://github.com/unawe/spaceawe/issues/33 .so I was put there logo.
I'm also looking for graphic of solar system. @Korczynska do you have it ? 
Thank you a lot.

**Comment by Korczynska** [comment]
Hey Vaclav, I asked teh designer to send me the picture. I will let you know when I reveive it.

**Comment by Korczynska** [comment]
Hi Vaclav, 
Here are some useful pictures : https://www.dropbox.com/sh/komwivqoja7g2dd/AADiWPYLQK8Ls_URcFHbnhQPa?dl=0 
And the planet system here: 
![planet_system](https://cloud.githubusercontent.com/assets/22144217/22776579/77ff796e-eeb0-11e6-9320-a56ef27b6dda.png)
Let me know if you need anything additional.
Thank you!
Audrey
