### ISSUE TITLE
Presentation of activities

### ISSUE THREAD

**Issue by jorgegrivero** [unawe/spaceawe#86]
Hi @vehrlich, 

Regarding the presentation of the activities http://www.space-awareness.org/en/activities/1615/know-your-planets/

We would like that the first section "Brief Description" and the last one "Conclusion" would not be collapsed like the other ones and they would always show the whole content.

Is that possible?

**Comment by vehrlich** [comment]
Hi @jorgegrivero ,
it's possible and it's done.
