### ISSUE TITLE
blank box when charging activities

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#93]
When charging more activities with "load more", there is a blank box where an activity should appear. It looks like there is nothing more to upload while there are still other boxes to be charged if we click again on "load more". 

Could you please check and replace the blank by a full box ? 

http://www.space-awareness.org/games/

**Comment by vehrlich** [comment]
That is because game 'PlanetHunters' has no cover asociated.
Just add cover in administration and it should be ok.
