### ISSUE TITLE
Search page 

### ISSUE THREAD

**Issue by Korczynska** [unawe/spaceawe#98]
Hello Vaclav, 
One of our partners pointed out that the search option in the website is missing. Indeed, this was something planned from the beginning and I gues changing of web developers, we forgot about this option.
Please check the PDF attached to see how this was planned on the home page + the search page design that should be working a bit like a google search engine. 
Please let me know if you need extra information.
Thanks!

[SpaceAw_web_v5_03-home page + category + search page.pdf](https://github.com/unawe/spaceawe/files/803123/SpaceAw_web_v5_03-home.page.category.search.page.pdf)

**Comment by vehrlich** [comment]
Sure I'll work on  this ticket and [this one](https://github.com/unawe/spaceawe/issues/40) I'll close

**Comment by vehrlich** [comment]
Now it's ok for desktop. But for mobile it's useless. If you have PDF with mobile version of search, please send it to me. Thank you.

**Comment by Korczynska** [comment]
I don't seem to have a PDF for mobile... The idea was to add a menu line in the left side menu on the mobile version with the search option there.
If you need a template, maybe I can ask our designer. 
Let me know.
